apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-cronjob.yaml
  - configmap.yaml
  - deployment.yaml
  - frontend.yaml
  - hpa.yaml
  - ingress.yaml
  - network-policy.yaml
  - lcp-core.yaml
  - lsd-core.yaml
  - postgres.yaml
  - pvc.yaml
  - redis.yaml
  - secret.yaml
  - service.yaml
  - servicemonitor.yaml
  - readium-core-configmap.yaml
  - readium-core-pvc.yaml
  - readium-core-secret.yaml
labels:
  - pairs:
      component: lcp-server
    includeSelectors: true
