apiVersion: v1
kind: Secret
metadata:
  name: lcp-secrets
  labels:
    app: lcp-server
type: Opaque
stringData:
  jwt-secret: 86877c9e39ef803e54a6598608346112cfdb3c1fec3307778c96b2ec89422859
  admin-username: amiradmin
  admin-password: e40949a95921fb6e
  admin-2fa-code: "65b5ec"
  postgres-user: lcp
  postgres-password: change-me-in-cluster
  db-dsn: >-
    postgres://lcp:change-me-in-cluster@lcp-postgres:5432/lcp?sslmode=disable
  monitoring-token: replace-with-admin-jwt
