apiVersion: v1
kind: ConfigMap
metadata:
  name: lcp-config
data:
  LCP_PROFILE: development
  PUBLIC_BASE_URL: https://dev.yourdomain.com
  LCP_PROVIDER_URI: https://dev.yourdomain.com
  STATUS_BASE_URL: https://status.yourdomain.com
