name: Link Checker

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: >
            --verbose
            --no-progress
            './**/*.md'
            './**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
