name: Link Checker

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: >
            --verbose
            --no-progress
            --root-dir .
            --exclude-path reports/coverage
            --exclude 'https://github.com/amirHdev/ebook-lcp-server/compare/.*'
            './**/*.md'
            './**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
