name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v5
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}
